name = "cloudoj"
compatibility_date = "2025-9-30"


# 开发环境配置
[dev]
port = 8080
local_protocol = "http"

[site]
bucket = "./web/dist"

[build]
command = "cd web && npm install && npm run build"
cwd = "web"
watch_dir = "./src"



[observability.logs]
enabled = true
