server:
  port: 8080
spring:
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  profiles:
    active: dev
  application:
    name: gateway
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost:3306}/cloud_oj?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
    hikari:
      minimum-idle: ${DB_POOL_SIZE:6}
      maximum-pool-size: ${DB_POOL_SIZE:6}
  jackson:
    default-property-inclusion: non_null
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=20m
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        namespace: 3fde09c7-0223-4dd8-9c14-888c9e282bc6
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        namespace: 3fde09c7-0223-4dd8-9c14-888c9e282bc6
        file-extension: yaml
        group: DEFAULT_GROUP
    gateway:
      mvc:
        routes:
          - id: core
            uri: lb://core
            filters:
              - StripPrefix=2
            predicates:
              - Path=/api/core/**
          - id: judge
            uri: lb://judge
            filters:
              - StripPrefix=2
            predicates:
              - Path=/api/judge/**
          - id: auth
            uri: lb://gateway
            filters:
              - StripPrefix=2
            predicates:
              - Path=/api/auth/**
    discovery:
      enabled: true
management:
  endpoint:
    health:
      show-details: always
app:
  token-valid-time: ${TOKEN_VALID_TIME:4}