name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release
  WORKING_DIR: judge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B cmake-build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Unix Makefiles"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build
        run: cmake --build cmake-build --config ${{env.BUILD_TYPE}}
        working-directory: ${{ env.WORKING_DIR }}
